spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hiberante:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
debug: true